### ISSUE TITLE
Not an Issue Post!

### ISSUE THREAD

**Issue by RemyThePianist** [johndpope/ConcertCreator2#2]
Hello, Johndpope! 

I am wondering why you created this? Are you planning on making a second Concert Creator Ai? That would lovely! I missed the accuracy it had. Especially with note durations compared to other transcription systems which don’t accurately measure the length of held notes. If this is not the point of this, I do wish you luck on your endeavors!

**Comment by johndpope** [comment]
this was a wrapper around the app to break into it - 
it got somewhere - but not far enough.
i can't understand how the founders shut shop. was amazing app.

**Comment by RemyThePianist** [comment]
Yah.. It was amazing. 

Where you able to get anywhere like INTO the code of how things were done? I understand the lack of like.. servers? And what not. But, are you able to extract certain things from the app? 

Honestly I can live with it being gone but, that midi humanizer (like the correct note lengths and stuff) it had that edited the MIDI file after its completion is what I want tbh..

**Comment by johndpope** [comment]
ask @PolyMeilex https://github.com/PolyMeilex/Neothesia

can probably get claude to spit something out.
